several improvements, Don't run in live mode

diff --git a/usr/bin/tuquito-update b/usr/bin/tuquito-update
--- a/usr/bin/tuquito-update
+++ b/usr/bin/tuquito-update
@@ -1,14 +1,16 @@
 #!/bin/bash
 export TEXTDOMAIN="tuquito-update"
 export TEXTDOMAINDIR="/usr/share/tuquito/locale"
-TUQUITOUPDATE=`ps -A | grep update-manager | wc -l`
-if [ $TUQUITOUPDATE != 0 ]; then
-	if [ "`whoami`" != "root" ]; then
-		zenity --error --text="$(gettext '<b><big>Error</big></b>\nAnother update-manager is already running, maybe in hidden mode.\nTry running on the console: <b>sudo tuquito-update</b>')" --title="$(gettext 'Tuquito Update - Error')" --window-icon=/usr/lib/tuquito/tuquito-update/logo.png
-		exit 1
-	else
-		kill -9 update-manager
+if [ "`mount | grep "aufs"`" = "" ]; then
+	TUQUITOUPDATE=`ps -A | grep update-manager | wc -l`
+	if [ $TUQUITOUPDATE != 0 ]; then
+		if [ "`whoami`" != "root" ]; then
+			zenity --error --text="$(gettext '<b><big>Error</big></b>\nAnother update-manager is already running, maybe in hidden mode.\nTry running on the console: <b>sudo tuquito-update</b>')" --title="$(gettext 'Tuquito Update - Error')" --window-icon=/usr/lib/tuquito/tuquito-update/logo.png
+			exit 1
+		else
+			kill -9 update-manager
+		fi
 	fi
+	/usr/lib/tuquito/tuquito-update/update-manager.py show 0 &
 fi
-/usr/lib/tuquito/tuquito-update/update-manager show 0 &
 exit 0
